### ISSUE TITLE
AttributeError: module 'readhw' has no attribute 'getInformationAboutCurrentComputer'

### ISSUE THREAD

**Issue by dmuiX** [sonnix-de/computerspende#7]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/daniel/Documents/computerspende/venv/lib/python3.8/site-packages/consolemenu/console_menu.py", line 169, in _wrap_start
    self._main_loop()
  File "/home/daniel/Documents/computerspende/venv/lib/python3.8/site-packages/consolemenu/console_menu.py", line 226, in _main_loop
    self.process_user_input()
  File "/home/daniel/Documents/computerspende/venv/lib/python3.8/site-packages/consolemenu/console_menu.py", line 311, in process_user_input
    self.select()
  File "/home/daniel/Documents/computerspende/venv/lib/python3.8/site-packages/consolemenu/console_menu.py", line 351, in select
    self.selected_item.action()
  File "/home/daniel/Documents/computerspende/venv/lib/python3.8/site-packages/consolemenu/items/function_item.py", line 35, in action
    self.return_value = self.function(*self.args, **self.kwargs)
  File "main.py", line 13, in showHardware
    print(hw.getInformationAboutCurrentComputer())
AttributeError: module 'readhw' has no attribute 'getInformationAboutCurrentComputer'

**Comment by dmuiX** [comment]
Entweder wir löschen diese Funktion oder wir bauen sie noch ein :D
