### ISSUE TITLE
KeyError: 'chassis'

### ISSUE THREAD

**Issue by dmuiX** [sonnix-de/computerspende#8]
[ WARN:0] global /tmp/pip-req-build-ms668fyv/opencv/modules/videoio/src/cap_v4l.cpp (893) open VIDEOIO(V4L2:/dev/video0): can't open camera by index
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    import IssueBuilder as IssueBuilder
  File "/home/daniel/Documents/computerspende/IssueBuilder.py", line 59, in <module>
    print(build())
  File "/home/daniel/Documents/computerspende/IssueBuilder.py", line 50, in build
    "name": category(lshwJson) 
  File "/home/daniel/Documents/computerspende/IssueBuilder.py", line 17, in category
    if lshwJson["configuration"]["chassis"] == 'notebook' or lshwJson["configuration"]["chassis"] == 'laptop':
KeyError: 'chassis'

**Comment by dmuiX** [comment]
Sobald chassis nicht vorkommt tritt dieser Fehler auf.
